#!/bin/bash
#
# turning on the card and getting _something_ is good enough for this test
# unlike fw test, no explicit setting of flags is done.
source `dirname $0`/common.sh

set_monitor $IFACE
link_up $IFACE
timeout 5 sudo tcpdump -i $IFACE -c1 >/dev/null || fail "didn't get any frames!"
