#!/bin/bash

source `dirname $0`/common.sh
[ "$1" != "noreload" ] && reload_card

# Mbps
TARGET_TX_TPUT=5
TARGET_RX_TPUT=5

start_mesh dev0
start_mesh ref0
if_up dev0
if_up ref0

# try 8787 -> ath9k_htc
start_traffic dev0 ref0
sleep 20
stop_traffic dev0 ref0

check_tput ref0 $TARGET_TX_TPUT "couldn't meet TX threshold!"

# try ath9k_htc -> 8787
start_traffic ref0 dev0
sleep 20
stop_traffic ref0 dev0

check_tput dev0 $TARGET_RX_TPUT "couldn't meet RX threshold!"

# if we got here, and both throughputs are above the threshold, the firmware
# didn't crash either

cleanup
