#!/bin/bash

source `dirname $0`/common.sh

CH=6
CAP_FILE=out.cap

[ "$1" != "noreload" ] && reload_card

set_monitor $IFACE
fw_set_ch $IFACE $CH
set_channel $MON_IFACE $CH

testmode $IFACE tx_preq $MON_IFACE
