#!/bin/bash
#
# turning on the card and getting _something_ is good enough for this test
source `dirname $0`/common.sh

[ "$1" != "noreload" ] && reload_card

set_monitor $IFACE
link_up $IFACE
sudo ./testmode.py -i$IFACE -t set_mac_ctl 0xffff
timeout 5 sudo tcpdump -i $IFACE -c1 &> /dev/null || fail "didn't get any frames!"
