#!/bin/bash
source `dirname $0`/common.sh

# test we can successfully change the wifi channel by observing a beacon from a
# known AP
KNOWN_SSID=${KNOWN_SSID:-cozybit}
KNOWN_CH=${KNOWN_CH:-11}

[ "$1" != "noreload" ] && reload_card

set_monitor $IFACE
link_up $IFACE
fw_set_ch $IFACE $KNOWN_CH
sudo timeout 3 tcpdump -i$IFACE 2> /dev/null | grep $KNOWN_SSID &> /dev/null || fail "SSID not found, must be wrong channel!"
