#!/bin/bash
source `dirname $0`/common.sh

CH=6
CAP_FILE=out.cap
PAYLOAD="01234567890123456789"

[ "$1" != "noreload" ] && reload_card

# must be in monitor for injection
set_monitor $IFACE
fw_set_ch $IFACE $CH
set_channel $MON_IFACE $CH

IFACE_ADDR=`if2mac $IFACE`

# start capturing on MON_IFACE
start_capture_filter_mac $MON_IFACE $CAP_FILE $IFACE &
sleep 2

BASE_ADDRESS="90:f6:52:76:4e:"
ADDRESS_RANGE=32
MIN_RATE=11

# iterate through all the addresses in the address range a few times 
# to minimize the possibility of the sniffer capturing high data rate frames
for i in {1..7}
do
	testmode $IFACE send_to_many_peers $PAYLOAD $BASE_ADDRESS $ADDRESS_RANGE
done

sleep 1
stop_all_captures
# inspect capture for frame

sudo chown $USER $CAP_FILE

FOUND=`tshark -r$CAP_FILE -Y"wlan.addr == $IFACE_ADDR" | wc -l`
[ "$FOUND" -lt 1 ] && fail "couldn't find frames from $IFACE_ADDR"

# Our test frames are UDP with udp port 0x123.  Look for that.
FOUND=`tshark -r$CAP_FILE -Y"wlan.addr == $IFACE_ADDR && udp.port == 0x123" | wc -l`
[ "$FOUND" -lt 1 ] && fail "Frames from $IFACE_ADDR have an invalid payload"

for (( i=0; i<$ADDRESS_RANGE; i++ ))
do
	DESTINATION=`printf "${BASE_ADDRESS}%02x\n" $i`
	FOUND=`tshark -r$CAP_FILE -Y"radiotap.datarate >= $MIN_RATE && wlan.ra == $DESTINATION" | wc -l`
	[ "$FOUND" -lt 1 ] && fail "couldn't find frames sent to $DESTINATION with datarate of $MIN_RATE or higher"
done

exit 0
