#!/bin/bash
source `dirname $0`/common.sh

COUNT=2             # send this many frames
RETRIES=5           # this many times
PASS=$[RETRIES * COUNT - 4]
CH=6
CAP_FILE=out.cap
MCAST_ADDR=224.4.5.6
PAYLOAD="01234567890123456789"

PHY=`if2phy $IFACE`

# join mesh
start_mesh dev0
if_up dev0

# start capturing on MON_IFACE
set_monitor $MON_IFACE
set_channel $MON_IFACE $CH
start_capture_filter_mac $MON_IFACE $CAP_FILE $IFACE &
sleep 2
cap_pid=$!

# set mcast retries
OLD_RETRIES=`sudo cat /sys/kernel/debug/ieee80211/$PHY/netdev:$IFACE/mesh_config/mcast_retries`
echo $RETRIES | sudo tee /sys/kernel/debug/ieee80211/$PHY/netdev:$IFACE/mesh_config/mcast_retries

# send a couple of frames, and look for a lot more in the cap
./drv_tx.py mcast $IFACE 2 $MCAST_ADDR:7890 $PAYLOAD

sleep 1
stop_all_captures

echo $OLD_RETRIES | sudo tee /sys/kernel/debug/ieee80211/$PHY/netdev:$IFACE/mesh_config/mcast_retries

# inspect capture for any frame from us
IFACE_ADDR=`if2mac $IFACE`
FOUND=`tshark -r$CAP_FILE -Y"wlan.addr == $IFACE_ADDR" | wc -l`
[ "$FOUND" -lt 1 ] && fail "couldn't find frames from $IFACE_ADDR"

# now check count
FOUND=`tshark -r$CAP_FILE -Y"wlan.addr == $IFACE_ADDR && ip.dst == $MCAST_ADDR && data.data == \"$PAYLOAD\"" | wc -l`
[ "$FOUND" -lt $PASS ] && fail "Not enough frames from $IFACE_ADDR found"

cleanup

