#!/bin/bash
source `dirname $0`/common.sh

# test we can successfully change the wifi channel by observing a beacon from a
# known AP
KNOWN_SSID=cozybit
KNOWN_CH=11

reload_card

set_monitor $IFACE
link_up $IFACE
sudo ./testmode.py -i$IFACE -t set_channel -a $KNOWN_CH
timeout 3 sudo tcpdump -i$IFACE | grep $KNOWN_SSID || fail "SSID not found, must be wrong channel!"
