#!/bin/bash
source `dirname $0`/common.sh

CH=6
CAP_FILE=out.cap
PAYLOAD="01234567890123456789"

if [ "$1" != "repeat" ]
then
	reload_card

	# must be in monitor for injection
	set_monitor $IFACE
	fw_set_ch $IFACE $CH
	set_channel $MON_IFACE $CH
fi

# start capturing on MON_IFACE
start_capture $MON_IFACE $CAP_FILE &
sleep 2
cap_pid=$!

# pew pew
testmode $IFACE send_data_multicast $PAYLOAD
testmode $IFACE send_data_multicast $PAYLOAD
testmode $IFACE send_data_multicast $PAYLOAD
testmode $IFACE send_data_multicast $PAYLOAD
testmode $IFACE send_data_multicast $PAYLOAD
testmode $IFACE send_data_multicast $PAYLOAD

sleep 1
sudo killall tcpdump
# inspect capture for frame
IFACE_ADDR=`if2mac $IFACE`
FOUND=`tshark -r$CAP_FILE -R"wlan.addr == $IFACE_ADDR" | wc -l`
[ "$FOUND" -lt 1 ] && fail "couldn't find frames from $IFACE_ADDR"

# Our test frames are UDP with udp port 0x123.  Look for that.
FOUND=`tshark -r$CAP_FILE -R"wlan.addr == $IFACE_ADDR && udp.port == 0x123" | wc -l`
[ "$FOUND" -lt 1 ] && fail "Frames from $IFACE_ADDR have an invalid payload"
