#!/bin/bash

source `dirname $0`/common.sh

CH=6
CAP_FILE=out.cap

[ "$1" != "noreload" ] && reload_card

set_monitor $IFACE
fw_set_ch $IFACE $CH
set_channel $MON_IFACE $CH

start_capture_filter_mac $MON_IFACE $CAP_FILE $IFACE &
sleep 2
cap_pid=$!

testmode $IFACE send_all $MON_IFACE

sleep 2
kill $cap_pid
